pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "SecureVault"
include ':app'
